name: Build release with baseline profile

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      check: true
      gen_baseline_profile: true
      build_release: true
    secrets:
      keystore_base64: ${{ secrets.KEYSTORE_BASE64 }}
      keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
      keystore_key_password: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
