name: Run CI

on:
  workflow_dispatch:

jobs:
  check:
    uses: ./.github/workflows/build.yaml
    with:
      check: true
      gen_baseline_profile: false
      release: false
    secrets:
      keystore_base64: ${{ secrets.KEYSTORE_BASE64 }}
      keystore_password: ${{ secrets.KEYSTORE_PASSWORD }}
      keystore_key_password: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
